### PR TITLE
fix(@kampus-apps/pano): add parsing on focus leave

### LINKED ISSUE #105: Parse title from link on creation

### PR DESCRIPTION
**Pull request by cansirin**
Fixes #105

This PR adds meta tags parsing process to focus on leave action.

### CODE REVIEW

File: apps/pano/src/routes/send.tsx [hunk 1]
```diff
@@ -87,7 +91,10 @@ const Send = () => {
             name="url"
             size="2"
             onPaste={(e) => {
-              onPaste(e.clipboardData.getData("text"));
+              fetchMetaTags(e.clipboardData.getData("text"));
+            }}
+            onBlur={(e) => {
+              fetchMetaTags(e.target.value);
```
Comment (usirin) [inline apps/pano/src/routes/send.tsx:97]: `onBlur` is still late for doing this. User needs to know that AFTER they leave the input, ONLY THEN it will be fetched, which is wrong IMO.

The correct way to fix this should be using a `debounced` callback for `onChange` event handler.

File: apps/pano/src/routes/send.tsx [hunk 2]
```diff
@@ -71,11 +71,15 @@ const Send = () => {
   const meta = fetcher.data?.meta;
   const error = fetcher.data?.error;
 
-  const onPaste = (url: string) => {
-    const formData = new FormData();
-    formData.set("url", url);
-    fetcher.submit(formData, { method: "post", action: "/api/parse-meta" });
-  };
+  const fetchMetaTags = (url: string) => {
```
Comment (usirin) [inline apps/pano/src/routes/send.tsx:74]: let's move this to a feature called `meta-tags`

**Review by usirin — CHANGES_REQUESTED** [review]

**Review by usirin — APPROVED** [review]

**Comment by usirin** [comment]
Merging this as this is an improvement over the current state, we can send another PR to improve on the points i've posted later.
